{
    'name': "Hotel Management System",
    'description': """Hotel Management System""",
    'owner': 'Veritiesoft',
    'version': '1.0',
    'category': 'Hotel',
    'sequence': -100,
    'price': '399',
    'currency': 'USD',
    'website': 'https://www.veritiesoft.com',
    'depends': [
        'base',
        'mail',
        'account',
        'product',
        'sale',
        'contacts',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/rule.xml',
        'data/hotel_sequence.xml',
        'data/hotel_amenity_type_data.xml',
        'data/hotel_amenity_data.xml',
        'data/hotel_bed_type_data.xml',
        'data/hotel_hotel_data.xml',
        'data/hotel_service_data.xml',
        'data/hotel_room_category_data.xml',
        'data/hotel_hotel_gallery_data.xml',
        'data/hotel_building_data.xml',
        'data/hotel_building_floor_data.xml',
        'data/hotel_room_data.xml',
        'data/hotel_rate_plan_data.xml',
        'data/hotel_tax.xml',
        'data/hotel_discount_data.xml',
        'report/hotel_reports.xml',
        'report/hotel_reservation_report_template.xml',
        'report/hotel_guest_folio_report_template.xml',
        'data/hotel_mail_templates.xml',
        'views/hotel_service_views.xml',
        'views/res_config_settings_views.xml',
        'views/hotel_amenity_type_views.xml',
        'views/hotel_amenity_views.xml',
        'views/hotel_bed_type_views.xml',
        'views/hotel_room_category_views.xml',
        'views/hotel_hotel_views.xml',
        'views/hotel_building_views.xml',
        'views/hotel_building_floor_views.xml',
        'views/hotel_room_views.xml',
        'views/hotel_rate_plan_views.xml',
        'views/hotel_discount_views.xml',
        'views/hotel_reservation_line_views.xml',
        'views/hotel_reservation_views.xml',
        'views/hotel_room_booking_views.xml',
        'views/hotel_housekeeping_views.xml',
        'views/hotel_maintenance_views.xml',
        'views/res_partner_inherit_views.xml',
        'views/hotel_guest_folio_views.xml',
        'wizards/hotel_task_assignment_wizard_views.xml',
        'views/hotel_menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'vs_hotel_management/static/src/scss/hotel_room.scss',
            'vs_hotel_management/static/src/scss/hotel_reservation.scss',
        ],
    },
    'application': True,
    'installable': True,
}
