from . import res_config_settings
from . import hotel_room_configuration
from . import hotel_room_category
from . import hotel_building_floor
from . import hotel_room
from . import hotel_hotel_image
from . import hotel_building
from . import hotel_conf
from . import hotel_hotel
from . import hotel_rate_plan
from . import hotel_discount
from . import hotel_reservation_line
from . import hotel_room_booking
from . import hotel_reservation